version: '3.8'

services:
  proxy:
    build:
      context: ./proxy
    volumes:
      - static_data:/vol/static
    ports:
        - 8080:8080


  ts-product:
    build: . 
    command: > 
     bash -c "python3 manage.py migrate &&
      gunicorn setup.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      ts-db

    volumes:
      - ./:/code
      - static_data:/vol/web
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
    - ts-db
  ts-db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=ts
        - POSTGRES_PASSWORD=tsdrf
        - POSTGRES_DB=ts_dev
  
volumes:
  postgres_data:
  static_data:

