services:
    database_postrgres:
        image: postgres
        environment: 
            POSTGRES_DB: products
            POSTGRES_USER: olist_django
            POSTGRES_PASSWORD: mudar123
        ports: 
            - "5432:5432"
        container_name: postgres_ts
        expose: 
            - "5432"

            