services:
    database_postgres:
        image: postgres
        environment: 
            POSTGRES_DB: products
            POSTGRES_USER: olist_django
            POSTGRES_PASSWORD: mudar123
        ports: 
            - "5432:5432"
        expose: 
            - "5432"
        container_name: postgres_ts
        networks:
            - connection
    dependecies:
        build: 
            dockerfile: Dockerfile
            context: .
        image: olistts/django_poetry
        ports: 
            - "8000:8000"
        networks:
            - connection
networks:
    connection:
        driver: bridge