version: '3.8'

services:
  ts-product:
    build: . 
    command: >
      sh -c "python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000 "
    depends_on:
      ts-db

     
    volumes:
      - ./:/code
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
    - ts-db
  ts-db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=ts
        - POSTGRES_PASSWORD=tsdrf
        - POSTGRES_DB=ts_dev
  
volumes:
    postgres_data: